name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cleanup MySQL data
        run: sudo rm -rf ./data/mysql || true

      # Step 2: Show current user
      - name: Who am I
        run: whoami

      # Step 3: Build Docker image
      - name: Build Docker image
        run: sudo docker build -t my-note-app .

      # Step 4: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Push image to DockerHub
      - name: Push Docker image
        run: |
          sudo docker tag my-note-app ${{ secrets.DOCKERHUB_USERNAME }}/note-app:1.0.1
          sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/note-app:1.0.1

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV


  deploy:
    runs-on: self-hosted
    needs: build
      # Step 6: Deploy with docker-compose
    steps:
      - name: Deploy with docker-compose
        run: |
          sudo docker-compose down
          sudo docker-compose up -d
