name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, note-app]


    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Show current user
      - name: Who am I
        run: whoami

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t my-note-app .

      # Step 4: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Push image to DockerHub
      - name: Push Docker image
        run: |
          docker tag my-note-app ${{ secrets.DOCKERHUB_USERNAME }}/my-note-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-note-app:latest

      # Step 6: Deploy with docker-compose
      - name: Deploy with docker-compose
        run: |
          docker-compose down
          docker-compose up -d
