name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Show current user
      - name: Who am I
        run: whoami

      # Step 3: Set up Python and run tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        env:
          USE_SQLITE: 'true'
        run: |
          python manage.py test --verbosity=2

      # Step 4: Login to DockerHub (before build to avoid 401 Unauthorized)
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/note-app:1.0.1 .

      # Step 6: Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/note-app:1.0.1

      # Step 7: Set IMAGE_TAG
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV


  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      # Step 1: Checkout repo (optional if you need compose files)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Pull image
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/note-app:1.0.1

      # Step 4: Deploy with docker-compose
      - name: Deploy with docker-compose
        run: |
          docker-compose down
          docker-compose up -d
