name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Show current user
      - name: Who am I
        run: whoami

      # Step 3: Set up Python and run tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        env:
          USE_SQLITE: 'true'
        run: |
          python manage.py test --verbosity=2

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t my-note-app .

      # Step 4: Login to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 5: Push image to DockerHub
      - name: Push Docker image
        run: |
          docker tag my-note-app ${{ secrets.DOCKERHUB_USERNAME }}/my-note-app:1.0.1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-note-app:1.0.1

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV


  deploy:
    runs-on: self-hosted
    needs: build
      # Step 6: Deploy with docker-compose
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to DockerHub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-note-app:1.0.1

      - name: Deploy with docker-compose
        run: |
          docker-compose down
          docker-compose up -d
